<?
$PERM["/"]["*"]="R";
$PERM["/"]["G8"]="W";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["3"]="D";
$PERM["bitrix"]["4"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["bitrix"]["5"]="D";
$PERM["kabinet-pokupatelya"]["*"]="D";
$PERM["kabinet-pokupatelya"]["G6"]="R";
$PERM["kabinet-pokupatelya"]["G1"]="D";
$PERM["kabinet-prodavtsa"]["G7"]="R";
$PERM["kabinet-prodavtsa"]["*"]="D";
$PERM["kabinet-prodavtsa"]["G1"]="X";
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>